baseURL: "https://jiejiefu.github.io/blog/"
title: "Jay Fu Blog"
theme: "PaperMod"

pagination:
  pagerSize: 10

params:
  env: production
  title: Jay Fu Blog
  description: Algorithm | Edge Computing | Software Engineer
  author: Jay Fu

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  profileMode:
    enabled: true
    title: "Jay Fu"
    subtitle: "Machine Learning | Edge Computing"

  ShowTableOfContents: true
  HighlightStyle: "monokai"
  ## Footer: "Â© 2026 Jay Fu"

  # hideCopyright: false      # ðŸ”¹ å¿…é ˆ
  # ShowCodeCopyButtons: true # ðŸ”¹ å¿…é ˆ

menu:
  main:
    - identifier: posts
      name: Posts
      url: posts/
      weight: 10